build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php: 8.1.10

filter:
  excluded_paths:
    - config/*
    - examples/*
    - tests/*
    - vendor/*
    - .github/*
    - .phan/*
