language: php

matrix:
  include:
    - php: 7.4
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml.dist

after_success: bash <(curl -s https://codecov.io/bash)
