language: php

matrix:
  include:
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

install:
  - curl -o config/cacert.pem https://curl.haxx.se/ca/cacert.pem
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_success: bash <(curl -s https://codecov.io/bash)
